backend:
    name: git-gateway
    branch: main

site_url: https://www.bedfordfineartgallery.com
logo_url: https://res.cloudinary.com/dg6smdedp/image/upload/logo.png
media_library:
  name: cloudinary
  config:
    cloud_name: dg6smdedp
    api_key: 874875498277852
    output_filename_only: true
show_preview_links: false
publish_mode: editorial_workflow

collections:
    - name: 'artists'
      label: 'Artists'
      label_singular: Artist
      editor:
          preview: false
      format: 'json'
      folder: 'cms/artists'
      create: true
      slug: '{{fields.slug}}'
      fields:
          - { label: 'Name', name: 'name', widget: 'string', required: true, pattern: ["^\\S+$", "Name cannot be empty"] }
          - { label: 'Alias', name: 'alias', widget: 'string', required: false }
          - { label: 'Tiny Description (shows next to name)', name: 'tinyDescription', widget: 'string' }
          - { label: 'Has Landing Page?', name: 'hasLandingPage', widget: 'boolean', default: false }
          - { label: 'Body', name: 'body', widget: 'markdown', required: false }
          - {
                label: 'Paintings',
                name: 'paintings',
                widget: 'relation',
                required: false,
                multiple: true,
                collection: 'paintings',
                search_fields: ['title', 'tinyDescription'],
                display_fields: ['title', 'tinyDescription'],
                value_field: 'slug',
            }
          - { label: 'Slug', name: 'slug', widget: 'string', required: true, hint: 'Example: a_t_smith_artist-html File name that will appear in the browser address bar. NEVER CHANGE THE SLUG ONCE IT IS CREATED. THIS WILL BREAK THE ARTIST ON THE SITE AND POSSIBLY HIS PAINTINGS.', pattern: ["^(\\w|-)+-html$", "Slug must contain only letters, numbers, dashes, or underscores, and must end in -html"]  }
          - {
                label: 'Meta Title',
                name: 'metaTitle',
                widget: 'text',
                required: false,
                hint: 'This will default to the name of the artist',
            }
          - {
                label: 'Meta Description',
                name: 'metaDescription',
                widget: 'text',
                required: false,
                hint: 'This will default to a preview from the body (about the first 250 characters)',
            }
          - {
                label: 'Meta Keywords',
                name: 'metaKeywords',
                widget: 'text',
                required: false,
                hint: 'Keywords for the artist separated by commas',
            }
    - name: 'paintings'
      label: 'Paintings'
      label_singular: Painting
      editor:
          preview: false
      format: 'json'
      folder: 'cms/paintings'
      create: true
      slug: '{{fields.slug}}'
      fields:
          - { label: 'Title', name: 'title', widget: 'string', hint: "Title of Painting\nExample: Ornery Duo", required: true }
          - { label: 'Tiny Description (shows beneath name)', name: 'tinyDescription', widget: 'string', required: false, hint: "Alternate name or nickname that artist may be known by ( helpful for SEO )\nExample: aka JDolph" }
          - { label: 'Dimensions', name: 'dimensions', widget: 'string', required: false, hint: "Painting medium, height and width, signed ( if applicable)\nExample: Oil on canvas, 18.75 x 14.75 inches / Signed upper left" }
          - {
                label: 'Gallery Crop Image',
                name: 'galleryCropImage',
                widget: 'image',
                allow_multiple: false,
                required: false,
                hint: ' Image dimensions: 392 x 261 with black background. Full painting (without frame) cropped image used on the main gallery pages. This will show on the gallery pages.'
            }
          - {
                label: 'Grid Image',
                name: 'gridImage',
                widget: 'image',
                allow_multiple: false,
                required: false,
                hint: 'Image dimensions: 392 x 261. Zoomed in (without frame) cropped image used on artist landing pages and the sold page. This will show on pages that list multiple paintings.'
            }
          - {
                label: 'Medium Res Image',
                name: 'mediumResImage',
                widget: 'image',
                allow_multiple: false,
                required: false,
                hint: "Keep width or height around 1200px depending on painting orientation. Full painting with fame cropped image for mobile devices."
            }
          - {
                label: 'High Res Image',
                name: 'highResImage',
                widget: 'image',
                allow_multiple: false,
                required: false,
                hint: 'Keep width or height around 2800px depending on painting orientation. Full painting with fame cropped image for desktop computers. This will show on the painting detail pages.'
            }
          - {
                label: 'Painting Width',
                name: 'paintingWidth',
                widget: 'number',
                value_type: float,
                required: true,
                hint: 'Example: 25 Width of painting, including frame. Number only. This is used for the art wall placer.'
            }
          - {
                label: 'Painting Height',
                name: 'paintingHeight',
                widget: 'number',
                value_type: float,
                required: true,
                hint: 'Example: 25 Width of painting, including frame. Number only. This is used for the art wall placer.'
            }
          - label: Highlights
            name: "highlights"
            widget: "list"
            summary: '{{fields.highlight}}'
            fields:
                - {label: Text, name: highlight, widget: string }
                - {
                    label: 'Paired Painting',
                    name: pairedPainting,
                    widget: relation,
                    multiple: false,
                    required: false,
                    collection: paintings,
                    hint: 'Painting that is sold as a pair with this one',
                    search_fields: ['title', 'tinyDescription'],
                    display_fields: ['title', 'tinyDescription'],
                    value_field: 'slug',
                  }
            default:
                - { highlight: 'Available for purchase' }
                - { highlight: 'Professionally conserved and framed' }
                - { highlight: 'Competitively Priced $X,XXX' }
                - { highlight: 'Custom framing available' }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true, hint: "Artist description/bio. Use 'Ctrl + Shift + V' to paste from a Word doc without the odd formatting." }
          - {
                label: 'Artist',
                name: 'artist',
                widget: 'relation',
                required: false,
                multiple: false,
                collection: 'artists',
                search_fields: ['name', 'tinyDescription'],
                display_fields: ['name', 'tinyDescription'],
                value_field: 'slug',
                hint: "Artist description/bio. Use 'Ctrl + Shift + V' to paste from a Word doc without the odd formatting."
            }
          - {
                label: 'Status',
                name: 'status',
                widget: 'select',
                default: 'None',
                options: ['None', 'New', 'Sold', 'Hold'],
                hint: 'Mark painting as new, sold or hold if applicable.',
            }
          - {
                label: 'Featured?',
                name: 'featured',
                widget: boolean,
                default: false,
                required: false,
                hint: 'Toggle on if painting is to be featured at the top of the gallery page.',
            }
          - {
                label: 'Scrolling Homepage Image?',
                name: 'scrollingHomepageImage',
                widget: boolean,
                default: false,
                required: false,
                hint: 'Toggle on if painting should be included in the homepage scrolling images.',
            }
          - {
                label: 'Categories',
                name: 'categories',
                widget: 'select',
                multiple: true,
                options: ['Landscape', 'Marine', 'Still Life', 'Genre', 'American Historic / Political', 'Sporting Art', 'Animal', 'Sculpture'],
                required: false,
            }
          - { label: 'YouTube Link', name: 'youtubeEmbedLink', widget: 'string', required: false, pattern: ["^((?:https?:)?\\/\\/)?((?:www|m)\\.)?((?:youtube\\.com|youtu.be))(\\/(?:[\\w\\-]+\\?v=|embed\\/|v\\/)?)([\\w\\-]+)(\\S+)?$", "Enter a valid YouTube URL"], hint: "Example link: https://www.youtube.com/embed/bGDNytl-QM0?rel=0 Can be obtained by viewing the video on your YouTube channel and clicking the 'share' button." }
          - { label: 'Slug', name: 'slug', widget: 'string', hint: 'Example: Example: albert_francis_king_fishing_hole-html File name that will appear in the browser address bar. NEVER CHANGE THE SLUG ONCE IT IS CREATED. THIS WILL BREAK THE PAINTING ON THE SITE AND POSSIBLY ITS ARTIST.', pattern: ["^(\\w|-)+-html$", "Slug must contain only letters, numbers, dashes, or underscores, and must end in -html"] }
          - {
                label: 'Meta Title',
                name: 'metaTitle',
                widget: 'text',
                required: false,
                hint: 'Example: Albert Francis King Painting - The Fishing Hole - 19th Century American Fine Art Title that will appear in the browser tab.'
            }
          - {
                label: 'Meta Description',
                name: 'metaDescription',
                widget: 'text',
                required: false,
                hint: "SEO description. Example: Albert Francis King was born in Pittsburgh, Pennsylvania and was recognized as Pittsburgh's primary still-life painter during the 19th century.",
            }
          - {
                label: 'Meta Keywords',
                name: 'metaKeywords',
                widget: 'text',
                required: false,
                hint: 'SEO keywords. Example: David John Gue, 1836 - 1917, American, 19th century artist, Breakers at Dawn, Oil on canvas, marine, marine artwork, artist, paintings, artwork,art work, painting, art, Bedford Fine Art Gallery, fine art, art gallery',
            }
    - name: 'articles'
      label: 'Articles'
      label_singular: Article
      editor:
          preview: false
      format: 'json'
      folder: 'cms/articles'
      create: true
      slug: '{{fields.slug}}'
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
                label: 'Publish Date',
                name: 'date',
                widget: 'datetime',
                required: false,
                date_format: 'MM/DD/YYYY',
                time_format: false,
            }
          - { label: 'Show Publish Date', name: 'showPublishDate', widget: 'boolean' }
          - {
                label: 'Grid Image',
                name: 'gridImage',
                widget: 'image',
                allow_multiple: false,
                required: false,
                hint: 'This will be the grid image for the post on the highlights page',
            }
          - {
                label: 'Image',
                name: 'image',
                widget: 'image',
                allow_multiple: false,
                required: false,
                hint: 'This will be the image for the post',
            }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Use control, shift, v to paste when copying from Microsoft Word' }
          - { label: 'YouTube Link', name: 'youtubeEmbedLink', widget: 'string', required: false, pattern: ["^((?:https?:)?\\/\\/)?((?:www|m)\\.)?((?:youtube\\.com|youtu.be))(\\/(?:[\\w\\-]+\\?v=|embed\\/|v\\/)?)([\\w\\-]+)(\\S+)?$", "Enter a valid YouTube URL"] }
          - label: "Additonal Link"
            name: "additionalLink"
            widget: "object"
            summary: '{{fields.text}} -> {{fields.link}}'
            required: false
            fields:
                - { label: 'Text', name: 'text', widget: 'string' }
                - { label: 'Link', name: 'link', widget: 'string' }
          - { label: 'Slug', name: 'slug', widget: 'string' }
          - {
                label: 'Meta Title',
                name: 'metaTitle',
                widget: 'text',
                required: false,
                hint: 'This will default to the title of the post',
            }
          - {
                label: 'Meta Description',
                name: 'metaDescription',
                widget: 'text',
                required: false,
                hint: 'This will default to a preview from the post (about the first 250 characters)',
            }
          - {
                label: 'Meta Keywords',
                name: 'metaKeywords',
                widget: 'text',
                required: false,
                hint: 'The keywords for this painting separated by commas',
            }
    - name: 'artLoversNicheArticles'
      label: 'Art Lovers Niche Articles'
      label_singular: Art Lovers Niche Article
      editor:
          preview: false
      format: 'json'
      folder: 'cms/artLoversNicheArticles'
      create: true
      slug: '{{fields.slug}}'
      fields:
          - {
                label: 'Publish Date',
                name: 'date',
                widget: 'datetime',
                required: false,
                date_format: 'MM/DD/YYYY',
                time_format: false,
            }
          - {
                label: 'Preview',
                name: 'preview',
                widget: 'text',
                hint: 'This will show on the highlights list page'
            }
          - { label: 'Body', name: 'body', widget: 'text' }
          - { label: 'Slug', name: 'slug', widget: 'string' }
          - {
                label: 'Meta Title',
                name: 'metaTitle',
                widget: 'text',
                required: false,
                hint: 'This will default to the title of the post',
            }
          - {
                label: 'Meta Description',
                name: 'metaDescription',
                widget: 'text',
                required: false,
                hint: 'This will default to a preview from the post (about the first 250 characters)',
            }
          - {
                label: 'Meta Keywords',
                name: 'metaKeywords',
                widget: 'text',
                required: false,
                hint: 'The keywords for this painting separated by commas',
            }
    - name: 'testimonials'
      label: 'Testimonials'
      label_singular: Testimonial
      editor:
          preview: false
      format: 'json'
      folder: 'cms/testimonials'
      create: true
      fields:
          - {
                label: 'Name',
                name: 'name',
                widget: string,
                required: true,
            }
          - {
                label: 'Long Testimonial',
                name: 'longTestimonial',
                widget: text,
                required: true,
            }
          - {
                label: 'Short Testimonial',
                name: 'shortTestimonial',
                widget: text,
                required: true,
            }
